version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Squirre1"
      MYSQL_DATABASE: "hotelManager"
      MYSQL_USER: "appUser"
      MYSQL_PASSWORD: "Squirre1"
    volumes:
     - /data/mysql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9000:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Squirre1
  hotel-manager:
    image: hotel-manager
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotelManager?autoReconnect=true&useSSL=false
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - /data/hotel-manager