version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Squirre1"
      MYSQL_DATABASE: "hotelManager"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "Squirre1"
    volumes:
     - mysqldata:/var/lib/mysql
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9000:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Squirre1
volumes:
  mysqldata:
    driver: "local"